# Generated by Django 5.0.6 on 2024-05-30 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_caption_alter_post_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="posts",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_post",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_likes",
            field=models.ManyToManyField(
                blank=True, related_name="post_image_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
